site_name: RusticAI Documentation
nav:
  - Home: index.md
  - Core:
      - Overview: core/index.md
      - Architecture: core/architecture.md
      - Agents: core/agents.md
      - Guilds: core/guilds.md
      - Messaging: core/messaging.md
      - Execution: core/execution.md
      - Dependencies: core/dependencies.md
  - API: api/index.md
  - Showcase: showcase/index.md
  - SerpAPI: agents/serpapi/index.md
  - Marvin: agents/marvin/index.md
  - LangChain: langchain/index.md
  - Litellm: agents/litellm/index.md
  - Ray: ray/index.md
  - Chroma: chroma/index.md
  - Playwright: agents/playwright/index.md
  - HuggingFace: agents/huggingface/index.md
  - Data Analyst: data-analyst/index.md
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          